= Profiles Special Interest Group Charter

== Introduction

The RISC-V Profiles SIG drives the strategy and policy of Profiles for identified RISC-V markets and coordinates with the Task Groups developing those Profiles.

// == Definitions 

== Background

RISC-V Profiles are named groupings of standard processor ISA bases plus extensions (each identified as “Mandatory” or “Optional”).  Profiles enable a market of compliant processor implementations and facilitate ecosystem support.  Profiles are released periodically to include newly ratified ISA extensions, as the RISC-V ISA evolves.  They facilitate long-term architectural continuity and managed evolution.  Profiles enable implementations that are feature-aligned across hardware providers, providing software development tools, operating systems, libraries, ABIs, and application software with a common target.  

// [PROVIDE CONTEXT ABOUT THE GROUP'S RELEVANCE AND ANY PERTINENT TECHNOLOGY].

== Objectives

The scope of the Profiles SIG includes the following activities:

*	Providing a forum for discussion of general Profiles-related issues and issues spanning multiple Profiles 
*	Performing periodic outreach and “Gap Analyses” of Profile needs for current and future RISC-V markets 
*	Using results from those Gap Analyses, determine what new Profiles are required and spawning new Task Groups as needed to develop them; examples might include proposing: 
**	Updated releases of existing Profiles, e.g. RVA23 to RVA24
**	Profiles for additional markets:  e.g. RVM (Microcontroller) Profile, HPC Profile, Automotive Profile, SoftCPU Profile
**	New types of Profiles, e.g. a Machine-level Profile 
*	Developing policies with respect to RISC-V Profiles supporting continuity and managed evolution of the architecture 
**	e.g. Deprecation and addition policies supporting forward & backward compatibility
*	Maintaining documents containing general information about Profiles that is independent of specific Profiles
**	e.g. Definitions of Profile families, types of optional extensions  

// == Exclusions (Optional)
// 
// While not currently in scope, the following items may be considered for future iterations:

== Collaborations

To fulfill its objectives, the Profiles SIG will coordinate with key stakeholders such as:

* Target markets
*	Software tools groups, regarding if/how Profiles are specified in the toolchain 
*	System software groups, regarding if/how execution of software that does not comply with a Profile is restricted 
*	RISC-V International groups such as TSC (ARC, Platforms, ISA-related TGs), CSC, Marketing) 
* Non-RISC-V organizations such as RISE 
